language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"

before_script:
  - "gem install compass"
  - "./node_modules/bower/bin/bower install"

after_script:
  - "./node_modules/grunt-cli/bin/grunt build"
